{"status": "broken", "attachments": [{"source": "ed520d9f-19d2-4332-868c-8406ac78d8fd-attachment.txt", "type": "text/plain", "name": "log"}, {"source": "da31216e-d0ec-489e-a94b-a7436f7a7b3d-attachment.txt", "type": "text/plain", "name": "stdout"}, {"source": "b774dfc0-1672-40ab-b3ed-82e81cffa5c4-attachment.txt", "type": "text/plain", "name": "stderr"}], "labels": [{"name": "suite", "value": "test_case_api"}, {"name": "host", "value": "DESKTOP-CLD22EL"}, {"name": "thread", "value": "18228-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "test_case_api"}], "stop": 1560331397226, "uuid": "b52b449b-4575-4c31-a81e-de873bf9548e", "historyId": "3e89f147022fc518fb81369f00690a19", "start": 1560331396795, "fullName": "test_case_api#test_cash_account_enquiry", "statusDetails": {"message": "UnicodeEncodeError: 'ascii' codec can't encode characters in position 405-408: ordinal not in range(128)", "trace": "def test_cash_account_enquiry():\n        print(\"----------------------------提现账户查询--------------------------\")\n        paths = \"/transaction/showWithdrawAccount.htm\"\n        pam = {\"partnerId\": global_parameter.PARTNERID, \"merNo\": global_parameter.MERNO_NO_USERID}\n    \n        r_obj = Public_Request()\n        r_resu = r_obj.public_request(pas=paths, parameters=pam)\n    \n>       print(json.dumps(r_resu.json(), indent=2, sort_keys=False, ensure_ascii=False))\nE       UnicodeEncodeError: 'ascii' codec can't encode characters in position 405-408: ordinal not in range(128)\n\ntest_case_api.py:32: UnicodeEncodeError"}, "name": "test_cash_account_enquiry"}