{"status": "broken", "attachments": [{"source": "fd2725b9-be33-45ac-bbe4-22192ee53d86-attachment.txt", "type": "text/plain", "name": "log"}, {"source": "295055b1-d639-4a6f-8856-d2daa000b362-attachment.txt", "type": "text/plain", "name": "stdout"}, {"source": "1fd7a96c-c38c-45be-a9dc-e0a817f7c06b-attachment.txt", "type": "text/plain", "name": "stderr"}], "labels": [{"name": "suite", "value": "test_case_api"}, {"name": "host", "value": "DESKTOP-CLD22EL"}, {"name": "thread", "value": "18228-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "test_case_api"}], "stop": 1560331398038, "uuid": "2a44fd04-3a48-499c-a14e-8511fa2d7437", "historyId": "9919740f899e71d46bc50e1eebbfa3cd", "start": 1560331398018, "fullName": "test_case_api#test_zhang_hu_select_no_merno", "statusDetails": {"message": "UnicodeEncodeError: 'ascii' codec can't encode characters in position 32-38: ordinal not in range(128)", "trace": "def test_zhang_hu_select_no_merno():\n    \n        print(\"-------------------------账户查询-merNo不填------------------------------\")\n        paths = \"/merchant/show.htm\"\n        pam = {\"partnerId\": global_parameter.PARTNERID}\n    \n        r_obj = Public_Request()\n        r_resu = r_obj.public_request(pas=paths, parameters=pam)\n    \n>       print(json.dumps(r_resu.json(),indent=2, sort_keys=False, ensure_ascii=False))\nE       UnicodeEncodeError: 'ascii' codec can't encode characters in position 32-38: ordinal not in range(128)\n\ntest_case_api.py:240: UnicodeEncodeError"}, "name": "test_zhang_hu_select_no_merno"}