{"status": "broken", "attachments": [{"source": "342f4fe7-5683-41c3-a2af-f26e15e6c331-attachment.txt", "type": "text/plain", "name": "log"}, {"source": "88b43d30-e317-44cd-942c-31e60e013598-attachment.txt", "type": "text/plain", "name": "stdout"}, {"source": "d6bb1bd0-2f09-4f78-a4eb-d13e45df1f60-attachment.txt", "type": "text/plain", "name": "stderr"}], "labels": [{"name": "suite", "value": "test_case_api"}, {"name": "host", "value": "DESKTOP-CLD22EL"}, {"name": "thread", "value": "18228-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython2"}, {"name": "package", "value": "test_case_api"}], "stop": 1560331397748, "uuid": "5296d8ea-d72d-47ea-b42e-f801e4eb90c3", "historyId": "1a91aff2afcc7f1fc6932e5db09b8370", "start": 1560331397706, "fullName": "test_case_api#test_yu_e_select", "statusDetails": {"message": "UnicodeEncodeError: 'ascii' codec can't encode characters in position 457-458: ordinal not in range(128)", "trace": "def test_yu_e_select():\n        print(\"----------------------------- 余额查询 -----------------------------\")\n        paths = \"/merchant/showBalance.htm\"\n        pam = {\"partnerId\": global_parameter.PARTNERID, \"merNo\": global_parameter.MERNO_NO_USERID}\n        r_obj = Public_Request()\n        r_resu = r_obj.public_request(pas=paths, parameters=pam)\n>       print(json.dumps(r_resu.json(), indent=2, sort_keys=False, ensure_ascii=False))\nE       UnicodeEncodeError: 'ascii' codec can't encode characters in position 457-458: ordinal not in range(128)\n\ntest_case_api.py:158: UnicodeEncodeError"}, "name": "test_yu_e_select"}